var DB2 = {
  spirits: [
    {
      nr: "10001",
      artikelid: "25053",
      varnummer: "100",
      namn: "Braastad XO",
      namn2: "",
      prisinklmoms: "442.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2000-08-07",
      slutlev: " ",
      varugrupp: "Cognac",
      forpackning: "Flaska",
      forslutning: "Naturkork",
      ursprung: "Cognac, Fine Champagne",
      ursprunglandnamn: "Frankrike",
      producent: "Tiffon",
      leverantor: "Arcus Sweden AB",
      argang: "",
      provadargang: "",
      alkoholhalt: "40%",
      modul: "",
      sortiment: "FS",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },
    {
      nr: "1001",
      artikelid: "190719",
      varnummer: "10",
      namn: "Vanlig Vodka",
      namn2: "",
      prisinklmoms: "195.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2006-04-01",
      slutlev: " ",
      varugrupp: "Okryddad sprit",
      forpackning: "Flaska",
      forslutning: "Skruvkapsyl",
      ursprung: "",
      ursprunglandnamn: "Sverige",
      producent: "Svensk Export Vodka AB",
      leverantor: "Fondberg",
      argang: "",
      provadargang: "",
      alkoholhalt: "37.5%",
      modul: "",
      sortiment: "FS",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },
    {
      nr: "1001201",
      artikelid: "51029",
      varnummer: "10012",
      namn: "Dworek Vodka",
      namn2: "",
      prisinklmoms: "190.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2004-12-06",
      slutlev: " ",
      varugrupp: "Okryddad sprit",
      forpackning: "Flaska",
      forslutning: "",
      ursprung: "",
      ursprunglandnamn: "Polen",
      producent: "Tarpan Fabryka Likierow",
      leverantor: "TIWA Trading AB",
      argang: "",
      provadargang: "",
      alkoholhalt: "37.5%",
      modul: "",
      sortiment: "FS",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },

    {
      nr: "1004703",
      artikelid: "723841",
      varnummer: "10047",
      namn: "Nils Oscar",
      namn2: "Celebration Ale",
      prisinklmoms: "43.70",
      volymiml: null,
      prisperliter: null,
      saljstart: "2013-02-01",
      slutlev: " ",
      varugrupp: "Öl, Ale",
      forpackning: "Flaska",
      forslutning: "",
      ursprung: "",
      ursprunglandnamn: "Sverige",
      producent: "Nils Oscar Company",
      leverantor: "The Nils Oscar Company AB",
      argang: "",
      provadargang: "",
      alkoholhalt: "9.4%",
      modul: "T5",
      sortiment: "TSE",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },
    {
      nr: "1004801",
      artikelid: "733051",
      varnummer: "10048",
      namn: "Rhum J.M",
      namn2: "",
      prisinklmoms: "729.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2013-03-01",
      slutlev: " ",
      varugrupp: "Rom, Mörk",
      forpackning: "Flaska",
      forslutning: "",
      ursprung: "Martinique",
      ursprunglandnamn: "Frankrike",
      producent: "Les Heritiers Crassous de Mede",
      leverantor: "Cask Sweden AB",
      argang: "2001",
      provadargang: "",
      alkoholhalt: "46.6%",
      modul: "T7",
      sortiment: "TSE",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },

    {
      nr: "1005001",
      artikelid: "733084",
      varnummer: "10050",
      namn: "Balcones Texas",
      namn2: "",
      prisinklmoms: "899.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2013-03-01",
      slutlev: " ",
      varugrupp: "Whisky, Malt",
      forpackning: "Flaska",
      forslutning: "",
      ursprung: "",
      ursprunglandnamn: "USA",
      producent: "Balcones Distilling",
      leverantor: "Cask Sweden AB",
      argang: "",
      provadargang: "",
      alkoholhalt: "52.2%",
      modul: "",
      sortiment: "TSE",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },
    {
      nr: "1005401",
      artikelid: "733429",
      varnummer: "10054",
      namn: "Linkwood",
      namn2: "the Octave",
      prisinklmoms: "1159.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2013-03-01",
      slutlev: " ",
      varugrupp: "Whisky, Malt",
      forpackning: "Flaska",
      forslutning: "",
      ursprung: "Skottland, Highlands, Speyside",
      ursprunglandnamn: "Storbritannien",
      producent: "Duncan Taylor Scotch Whisky",
      leverantor: "Clydesdale AB",
      argang: "1989",
      provadargang: "",
      alkoholhalt: "51.7%",
      modul: "",
      sortiment: "TSE",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },
    {
      nr: "1005502",
      artikelid: "733446",
      varnummer: "10055",
      namn: "Marolo",
      namn2: "Grappa di Arneis Vigneto Renesio",
      prisinklmoms: "481.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2013-03-01",
      slutlev: " ",
      varugrupp: "Grappa och Marc, Grappa",
      forpackning: "Flaska",
      forslutning: "Naturkork",
      ursprung: "",
      ursprunglandnamn: "Italien",
      producent: "Distilleria St Teresa dei Frat",
      leverantor: "Haugen-Gruppen AB",
      argang: "",
      provadargang: "",
      alkoholhalt: "50%",
      modul: "T7",
      sortiment: "TSE",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },
    {
      nr: "1010501",
      artikelid: "659534",
      varnummer: "10105",
      namn: "Genuin 25",
      namn2: "",
      prisinklmoms: "149.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2012-09-01",
      slutlev: " ",
      varugrupp: "Okryddad sprit",
      forpackning: "Flaska",
      forslutning: "Skruvkapsyl",
      ursprung: "",
      ursprunglandnamn: "Sverige",
      producent: "Svensk Vodka i Motala AB",
      leverantor: "Svensk Vodka i Motala AB",
      argang: "",
      provadargang: "",
      alkoholhalt: "25%",
      modul: "",
      sortiment: "TST",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },
    {
      nr: "191801",
      artikelid: "23196",
      varnummer: "1918",
      namn: "Mousserande Jordgubbsdryck",
      namn2: "Alkoholfri",
      prisinklmoms: "33.00",
      volymiml: null,
      prisperliter: null,
      saljstart: "2000-05-08",
      slutlev: " ",
      varugrupp: "Alkoholfritt, Mousserande",
      forpackning: "Flaska",
      forslutning: "",
      ursprung: "",
      ursprunglandnamn: "\u00c3\u2013sterrike",
      producent: "Schloss Raggendorf",
      leverantor: "Nigab",
      argang: "",
      provadargang: "",
      alkoholhalt: "0%",
      modul: "",
      sortiment: "FS\u00c3\u2013",
      ekologisk: "0",
      koscher: "0",
      stock: "10",
    },
  ],
};
